name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
- name: Lighthouse CI Action
  uses: treosh/lighthouse-ci-action@v2
  with:
    # List of URL(s) to analyze
    urls: # optional
    # Number of runs to do per URL
    runs: # optional, default is 1
    # Path to a Lighthouse budgets.json file
    budgetPath: # optional
    # Path to a LHCI lighthouserc.json file
    configPath: # optional
    # 
    temporaryPublicStorage: # optional
    # Address of a LHCI server
    upload.serverBaseUrl: # optional
    # API token to push to LHCI server
    upload.token: # optional
    
    name: Lighthouse
on: push # For every push, this action will be triggered
jobs:
  lighthouse:
    runs-on: ubuntu-latest #OS
    steps:
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls:
            https://ramanpriya.github.io/Lighthouse-CI-Demo/
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci' # This will save the Lighthouse results as .json files
